# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "install.packages(c('ps'), repos = 'http://cran.rstudio.com/')"  ; fi

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

os:
  - linux
  - osx

matrix:
  exclude:
    -
      os: osx
      r: oldrel
    -
      os: osx
      r: devel
