# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

os:
  - linux
  - osx

matrix:
  exclude:
    -
      os: osx
      r: oldrel
    -
      os: osx
      r: devel
